blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/muhittincamdali/SwiftUI-Data-Visualization#readme
    about: Check out the documentation first
  - name: 💬 Discussions
    url: https://github.com/muhittincamdali/SwiftUI-Data-Visualization/discussions
    about: Ask questions and discuss ideas
